### ISSUE TITLE
Enable configuration of callback_time periodicity.

### ISSUE THREAD

**Issue by julien-c** [MA3STR0/kimsufi-crawler#24]
I'm missing availabilities because the servers apparently get ordered (perhaps programmatically) in less than the 15 seconds it takes for the crawler to respawn. 

I know there's a rate limit set up by OVH, but I believe it's less than `15sec` (I think it's 500 calls per hour-long slot).

**Comment by julien-c** [comment]
Great, thanks! By the way I managed to get the server I wanted :)

**Comment by MA3STR0** [comment]
Cool, happy to hear that!
