### ISSUE TITLE
needs an update

### ISSUE THREAD

**Issue by cronner** [MA3STR0/kimsufi-crawler#27]
needs an update of server types missing KS-2SSD etc
and can see that "zone":"fr"}, is missing?

https://ws.ovh.com/dedicated/r2/ws.dispatcher/getAvailability2

**Comment by MA3STR0** [comment]
Good point;
You can submit a pull request, or I will try to implement it on the weekend

**Comment by MA3STR0** [comment]
By the way, `"fr"` is just a meta-zone, I may implement meta-zones support but for now you can ignore it because it's redundant anyway ("fr" will also trigger "gra" alarm)

**Comment by MA3STR0** [comment]
Fixed
