### ISSUE TITLE
Looks like not working

### ISSUE THREAD

**Issue by soar** [MA3STR0/kimsufi-crawler#28]
I have run script just now, when I see available servers in web-interface:

![2015-04-18 12-06-29 kimsufi affordable dedicated server - mozilla firefox](https://cloud.githubusercontent.com/assets/30570/7214788/b3028c2e-e5c3-11e4-9f26-04901db3816b.png)

But there are not any announcements in console or on my email:

```
# python crawler.py          
2015-04-18 12:03:22,697 SMTP server check passed           
2015-04-18 12:03:22,697 Notification system check passed   
2015-04-18 12:03:22,698 Starting IO loop
```

My `config.json`:

```
{                                           
    "servers": ["KS-2", "KS-2 SSD", "KS-3"],
    "zones": ["rbx", "sbg"],                
    "notifier": "email",                    
    "from_email": "<gmail-account>",       
    "from_pwd": "<password>",     
    "from_smtp_host": "smtp.gmail.com",     
    "to_email": "<my-email>",              
    "crawler_interval": 20                  
}                                           
```

Here is content of `https://ws.ovh.com/dedicated/r2/ws.dispatcher/getAvailability2` at this time:

http://pastebin.com/rH9mAk9A

**Comment by soar** [comment]
Oh, sorry.. I have updated my config file to:

```
"servers": ["KS-2a", "KS-2b", "KS-2c"]
```

... and script works now. You should write about this to README, I think.

**Comment by MA3STR0** [comment]
Right, good idea
