### ISSUE TITLE
Add IRC support for notifier

### ISSUE THREAD

**Issue by lamperi** [MA3STR0/kimsufi-crawler#30]
A good idea would be to add some kind of support for IRC notifier. Running crawler could spawn an IRC connection, and messages could be delivered as private or channel messages.
Additional config keys would be at least IRC server, IRC nick, message target.

There seems to be a library in pypi to support IRC protocol with tornado: https://pypi.python.org/pypi/tornado-irc/0.0.1

**Comment by MA3STR0** [comment]
XMPP support has been recently added which I guess can substitute IRC for now. Otherwise, pull requests are appreciated.
