### ISSUE TITLE
Test function

### ISSUE THREAD

**Issue by Valcorb** [MA3STR0/kimsufi-crawler#38]
Would it be possible to implement a test feature that sends an SMS / Email to see if everything is working correctly? I don't believe I'm getting an e-mail.

**Comment by MA3STR0** [comment]
There is always a test for smtp config, it tries to connect to mail server on startup to check credentials. But sending actual test mail is also a good idea.

I will think about it, maybe some shell argument like

     ./crawler.py -test

Besides, if you are looking for KS-1 then its about one mail per week.

**Comment by Valcorb** [comment]
Yeah that would be awesome :)
I am indeed looking for KS-1, it's pretty hard to get it :(

**Comment by FrozenBeard** [comment]
Has this been implemented yet? It looks like all my settings are correct but I yet again missed the server I wanted to buy and I did not get an email when it was available.

**Comment by MA3STR0** [comment]
It's implemented; SMTP config is always checked automatically during startup. If credentials are wrong you will get an error message in terminal. If you have doubt, the easiest way to double-check: put some more popular servers in your config (eg KS-4) and see if you get notifications for it.
