### ISSUE TITLE
Will this work with the new KS-4B type servers?

### ISSUE THREAD

**Issue by FrozenBeard** [MA3STR0/kimsufi-crawler#48]
KS-4B is one of the new 2016 models, its not listed in https://github.com/MA3STR0/kimsufi-crawler/blob/master/mapping/server_types.json
Would adding it to this json file allow it to be searched?

**Comment by MA3STR0** [comment]
KS-4B was included in the latest script version.
Just run `git pull` and it should work.

**Comment by d-van-gorkom** [comment]
thank you
