### ISSUE TITLE
Feature request: Alarm sound

### ISSUE THREAD

**Issue by 01271** [MA3STR0/kimsufi-crawler#51]
I have my script set up but I want to make my computer emit an alarm sound as well as have a push notification on screen.

I tried to use sys.stdout.write('\a') but when I put it on line 111 of the script the alarm went off seemingly at random.
It would be nice to my computer checking without my needing to look at the screen.

**Comment by mthoretton** [comment]
I added a notifier "FileNotifier" and installed nginx on the vagrant where I run the crawler. FIleNotifier will change the file served by nginx.
I use https://chrome.google.com/webstore/detail/distill-web-monitor/inlikjemeeknofckkjolnjbpehgadgge?hl=fr to check the webpage at home or outside (even on my phone).
You have a lot of options: beautiful "Audio Clip", browser desktop notifications, mails ...

Ok, it's a bit hacky.

**Comment by MA3STR0** [comment]
@mthoretton how about sharing your FileNotifier with a pull request? ;)

**Comment by mthoretton** [comment]
Yes sure, I totally forgot this weekend sorry :/ I've created a PR #55

**Comment by MA3STR0** [comment]
Added terminal bell
