### ISSUE TITLE
Does notify for KS-2A

### ISSUE THREAD

**Issue by joggesan** [MA3STR0/kimsufi-crawler#64]
I have not yet received a notification for a ks-2a even though it has been available while i was running your script. I have tested succesfully with ks-3a and ks-2e. I have tried the online notifiers and they seem to have the same problem about not notifying for ks-2a.
I'm sorry if this is not a real problem, but i thought they might have changed the link for ks-2a or something.
Thank you for your script and time!

**Comment by Zeg9** [comment]
did it end up working ?
because I have the same problem, I even got notified a few times for KS-1 but never for KS-2A
